---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - curl
    - fasd
    - git
    - hub
    - nvm
    - vim
    - wget
    - zsh
    - openssl
    - coreutils
    - findutils

- name: Install Homebrew Cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - atom
    - github-desktop

- name: Cleanup Brew packages
  command: brew cleanup
